name: Deploy

on:
  release:
    types: [ prereleased ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{ secrets.SSH_HOST_DEV }}
            USER_NAME: ${{ secrets.USER_NAME_DEV }}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
              cd /var/www/ghatest && 
              sudo su www -c "git fetch" && 
              sudo su www -c "git checkout ${GITHUB_REF_NAME}" &&
              sudo su www -c "source venv/bin/activate" && 
              sudo su www -c "pip uninstall -yr requirements.txt" && 
              sudo su www -c "pip install -r requirements.txt" && 
              sudo su www -c "pip install gunicorn" && 
              sudo systemctl restart ghatest.service
              '